import {faHeadphones, faRefresh, faTag, faTruck} from '@fortawesome/free-solid-svg-icons';
import basic_diamond from '../assets/Diamond_Basics.png';
import earrings from '../assets/Earrings.png';
import necklaces from '../assets/Necklaces.png';
import rings from '../assets/Rings.png';
import diamond from '../assets/img-diamond.png';
import banner_1 from '../assets/diamond-jewelry.png';
import banner_2 from '../assets/Diamond_rings.png';
import banner_3 from '../assets/Lab_Grown_Diamonds.png';
import jewelry from '../assets/jewelry.png';

export const jewelries = [
	{logo: basic_diamond, title: 'Diamond Basics', link: '/jewelry/diamond-jewelry'},
	{logo: necklaces, title: 'Necklaces', link: '/jewelry/necklaces'},
	{logo: earrings, title: 'Earrings', link: '/jewelry/earrings'},
	// { logo: basic_diamond, title: "Bracelets" },
	{logo: rings, title: 'Rings', link: '/jewelry/rings'},
];

export const list = [
	{
		icon: faTruck,
		title: 'Free Delivery',
		subtitle: 'Orders from all item',
	},
	{
		icon: faRefresh,
		title: 'Return & Refund',
		subtitle: 'Money back guarantee',
	},
	{
		icon: faTag,
		title: 'Discount',
		subtitle: 'On every order over 40%',
	},
	{
		icon: faHeadphones,
		title: 'Support 24/7',
		subtitle: 'Contact us 24 hours a day',
	},
];

export const Shape = [
	'Round',
	'Princess',
	'Cushion',
	'Oval',
	'Emerald',
	'Pear',
	'Asscher',
	'Heart',
	'Radiant',
	'Marquise',
];

export const metalJewelry = ['White Gold', 'Yellow Gold', 'Platinum'];

export const listDiamond = [
	{
		img: diamond,
		title: '1.01 Carat H-VS2 Princess Cut Diamond',
		price: '$2,720',
		carat: '1.01',
		color: 'H',
		clarity: 'VS2',
		shipping_time: 'Sep 17',
		shape: 'Pear',
		icon: '',
		cut: '',
	},
	{
		img: diamond,
		title: '1.01 Carat H-VS2 Princess Cut Diamond',
		price: '$2,720',
		carat: '1.01',
		color: 'H',
		clarity: 'VS2',
		shipping_time: 'Sep 17',
		shape: 'Pear',
		icon: '',
		cut: '',
	},
	{
		img: diamond,
		title: '1.01 Carat H-VS2 Princess Cut Diamond',
		price: '$2,720',
		carat: '1.01',
		color: 'H',
		clarity: 'VS2',
		shipping_time: 'Sep 17',
		shape: 'Pear',
		icon: '',
		cut: '',
	},
	{
		img: diamond,
		title: '1.01 Carat H-VS2 Princess Cut Diamond',
		price: '$2,720',
		carat: '1.01',
		color: 'H',
		clarity: 'VS2',
		shipping_time: 'Sep 17',
		shape: 'Pear',
		icon: '',
		cut: '',
	},
	{
		img: diamond,
		title: '1.01 Carat H-VS2 Princess Cut Diamond',
		price: '$2,720',
		carat: '1.01',
		color: 'H',
		clarity: 'VS2',
		shipping_time: 'Sep 17',
		shape: 'Pear',
		icon: '',
		cut: '',
	},
	{
		img: diamond,
		title: '1.01 Carat H-VS2 Princess Cut Diamond',
		price: '$2,720',
		carat: '1.01',
		color: 'H',
		clarity: 'VS2',
		shipping_time: 'Sep 17',
		shape: 'Pear',
		icon: '',
		cut: '',
	},
	{
		img: diamond,
		title: '1.01 Carat H-VS2 Princess Cut Diamond',
		price: '$2,720',
		carat: '1.01',
		color: 'H',
		clarity: 'VS2',
		shipping_time: 'Sep 17',
		shape: 'Pear',
		icon: '',
		cut: '',
	},
	{
		img: diamond,
		title: '1.01 Carat H-VS2 Princess Cut Diamond',
		price: '$2,720',
		carat: '1.01',
		color: 'H',
		clarity: 'VS2',
		shipping_time: 'Sep 17',
		shape: 'Pear',
		icon: '',
		cut: '',
	},
	{
		img: diamond,
		title: '1.01 Carat H-VS2 Princess Cut Diamond',
		price: '$2,720',
		carat: '1.01',
		color: 'H',
		clarity: 'VS2',
		shipping_time: 'Sep 17',
		shape: 'Pear',
		icon: '',
		cut: '',
	},
	{
		img: diamond,
		title: '1.01 Carat H-VS2 Princess Cut Diamond',
		price: '$2,720',
		carat: '1.01',
		color: 'H',
		clarity: 'VS2',
		shipping_time: 'Sep 17',
		shape: 'Pear',
		icon: '',
		cut: '',
	},
	{
		img: diamond,
		title: '1.01 Carat H-VS2 Princess Cut Diamond',
		price: '$2,720',
		carat: '1.01',
		color: 'H',
		clarity: 'VS2',
		shipping_time: 'Sep 17',
		shape: 'Pear',
		icon: '',
		cut: '',
	},
	{
		img: diamond,
		title: '1.01 Carat H-VS2 Princess Cut Diamond',
		price: '$2,720',
		carat: '1.01',
		color: 'H',
		clarity: 'VS2',
		shipping_time: 'Sep 17',
		shape: 'Pear',
		icon: '',
		cut: '',
	},
	{
		img: diamond,
		title: '1.01 Carat H-VS2 Princess Cut Diamond',
		price: '$2,720',
		carat: '1.01',
		color: 'H',
		clarity: 'VS2',
		shipping_time: 'Sep 17',
		shape: 'Pear',
		icon: '',
		cut: '',
	},
];

export const marks = {
	0: 'K',
	1: 'J',
	2: 'I',
	3: 'H',
	4: 'G',
	5: 'F',
	6: 'E',
	7: 'D',
};

export const listBanner = [{img: banner_1}, {img: banner_2}, {img: banner_3}];

export const listJewelry = [
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
	{
		img: jewelry,
		title: 'Classic Four-Prong Solitaire Engagement Ring in 18k White Gold',
		price: '$600',
		discountPrice: '$450',
		rating: 5,
	},
];
